server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    prefer-ip-address: true

security:
  user:
    name: user
    password: 12345

person-service:
  ribbon:
    listOfServers: localhost:8080, localhost:8082
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    eureka.enabled: true
