spring:
  application:
    name: person-service
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: test

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

ribbon:
  listOfServers: localhost:8080, localhost:8082
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  eureka.enabled: true
